name: gits_flutter_ui_component
description: A new Flutter project.

publish_to: "none"

version: 0.6.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # components
  table_calendar: ^3.0.7
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0
  flutter_svg: ^1.1.5
  device_frame: ^1.1.0
  flutter_markdown: ^0.6.13
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git

  # navigation
  go_router: ^5.1.5

  # state management
  flutter_bloc: ^8.1.1

  # utils
  intl: ^0.17.0
  collection: ^1.16.0
  url_launcher: ^6.1.6
  equatable: ^2.0.5
  gits_extension: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/markdown/
    - CHANGELOG.md
    - Contributors.md
